base_config: base.yaml
experiment_name: rgb_real_msi_unet_resnet34
modality: rgb_real_msi
in_channels: 7
augmentations:
  brightness: 0.10
  contrast: 0.10
  noise_std: 0.005
paths:
  patch_manifest_dir: data/patches/rgb_real_msi
  train_patch_manifest: data/patches/rgb_real_msi/train_patches.csv
  val_patch_manifest: data/patches/rgb_real_msi/val_patches.csv
  test_patch_manifest: data/patches/rgb_real_msi/test_patches.csv
  normalization_stats: data/processed/rgb_real_msi_normalization.json
