base_config: ../base.yaml
experiment_name: rgb_unet_resnet34
modality: rgb
in_channels: 3
paths:
  patch_manifest_dir: data/patches/rgb
  train_patch_manifest: data/patches/rgb/train_patches.csv
  val_patch_manifest: data/patches/rgb/val_patches.csv
  test_patch_manifest: data/patches/rgb/test_patches.csv
  normalization_stats: data/processed/rgb_normalization.json
